import type { Project, Skill, BlogPost, Testimonial, Translations } from "@/types"

export const projects: Project[] = [
  {
    id: "1",
    title: "Expense Tracker App",
    description: "Modern expense tracking with Node.js",
    image: "/expenseapp.png?height=300&width=400",
    category: "web",
    technologies: ["Node.js"],
    githubUrl: "https://github.com/Quammy93/Node.js_Backend/tree/main/ExpenseTracker",
  },
  {
    id: "2",
    title: "Personal BlogPost App",
    description: "Modern blog post app where you can write and publish articles",
    image: "/Blogapp.jpg?height=300&width=400",
    category: "web",
    technologies: ["Node.js"],
    githubUrl: "https://github.com/Quammy93/Node.js_Backend/tree/main/personal-blog",
  },
  {
    id: "3",
    title: "Task Management App",
    description: "Cross-platform mobile app built with React Native",
    image: "/placeholder.svg?height=300&width=400",
    category: "mobile",
    technologies: ["React Native", "Firebase", "Redux"],
    liveUrl: "https://example.com",
    githubUrl: "https://github.com/example",
  },
  {
    id: "4",
    title: "Brand Identity Design",
    description: "Complete brand identity for tech startup",
    image: "/placeholder.svg?height=300&width=400",
    category: "design",
    technologies: ["Figma", "Adobe Creative Suite"],
    liveUrl: "https://behance.net/example",
  },
]

export const skills: Skill[] = [
  { name: "Html", level: 94, category: "frontend"},
  { name: "CSS", level: 94, category: "frontend"},
  { name: "React/Next.js", level: 95, category: "frontend" },
  { name: "TypeScript", level: 80, category: "frontend" },
  { name: "Tailwind CSS", level: 76, category: "frontend" },
  { name: "Node.js", level: 88, category: "backend" },
  { name: "Python", level: 85, category: "backend" },
  { name: "Django", level: 82, category: "backend" },
  { name: "Flask", level: 78, category: "backend" },
  { name: "Express.js", level: 80, category: "backend" },
  { name: "javascript", level: 60, category: "backend"},
  { name: "PostgreSQL", level: 80, category: "backend" },
  { name: "MangoDb", level: 94, category: "backend"},
  { name: "Git/GitHub", level: 92, category: "tools" },
  { name: "Docker", level: 75, category: "tools" },
  { name: "AWS", level: 70, category: "tools" },
  { name: "Azure", level: 74, category: "tools" },
]

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Future of Web Development",
    excerpt: "Exploring the latest trends and technologies shaping the future of web development...",
    image: "/placeholder.svg?height=200&width=400",
    date: "2024-12-15",
    readTime: "5 min read",
    slug: "future-of-web-development",
  },
  {
    id: "2",
    title: "Building Scalable React Applications",
    excerpt: "Best practices and patterns for creating maintainable and scalable React applications...",
    image: "/placeholder.svg?height=200&width=400",
    date: "2024-12-10",
    readTime: "8 min read",
    slug: "scalable-react-applications",
  },
  {
    id: "3",
    title: "Design Systems in Modern UI",
    excerpt: "How to create and maintain consistent design systems for better user experiences...",
    image: "/placeholder.svg?height=200&width=400",
    date: "2024-12-05",
    readTime: "6 min read",
    slug: "design-systems-modern-ui",
  },
]

export const testimonials: Testimonial[] = [
   {
     id: "3",
    name: "Emily Rodriguez",
     role: "Product Manager",
     company: "InnovateCorp",
    content: "Outstanding technical skills combined with excellent communication. A pleasure to work with.",
    image: "/placeholder.svg?height=60&width=60",
   },
]

export const translations: Translations = {
  en: {
    "nav.home": "Home",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.blog": "Blog",
    "nav.testimonials": "Testimonials",
    "nav.contact": "Contact",
    "hero.title": "Hello, I'm Your Name",
    "hero.subtitle": "Full Stack Developer & Creative Problem Solver",
    "hero.viewWork": "View My Work",
    "hero.getInTouch": "Get In Touch",
    "projects.title": "Featured Projects",
    "projects.all": "All",
    "projects.web": "Web Apps",
    "projects.mobile": "Mobile",
    "projects.design": "Design",
    "skills.title": "Skills & Expertise",
    "skills.frontend": "Frontend Development",
    "skills.backend": "Backend Development",
    "skills.tools": "Tools & Others",
    "blog.title": "Latest Blog Posts",
    "blog.readMore": "Read More →",
    "testimonials.title": "What Clients Say",
    "contact.title": "Get In Touch",
    "contact.info": "Contact Information",
    "contact.followMe": "Follow Me",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.captcha": "Security Check",
    "contact.send": "Send Message",
    "footer.about": "About",
    "footer.description": "Passionate developer creating innovative solutions and beautiful user experiences.",
    "footer.quickLinks": "Quick Links",
    "footer.services": "Services",
    "footer.social": "Social Media",
  },
  es: {
    "nav.home": "Inicio",
    "nav.projects": "Proyectos",
    "nav.skills": "Habilidades",
    "nav.blog": "Blog",
    "nav.testimonials": "Testimonios",
    "nav.contact": "Contacto",
    "hero.title": "Hola, soy Tu Nombre",
    "hero.subtitle": "Desarrollador Full Stack y Solucionador Creativo",
    "hero.viewWork": "Ver Mi Trabajo",
    "hero.getInTouch": "Contactar",
    "projects.title": "Proyectos Destacados",
    "projects.all": "Todos",
    "projects.web": "Apps Web",
    "projects.mobile": "Móvil",
    "projects.design": "Diseño",
    "skills.title": "Habilidades y Experiencia",
    "skills.frontend": "Desarrollo Frontend",
    "skills.backend": "Desarrollo Backend",
    "skills.tools": "Herramientas y Otros",
    "blog.title": "Últimas Publicaciones",
    "blog.readMore": "Leer Más →",
    "testimonials.title": "Lo Que Dicen Los Clientes",
    "contact.title": "Contactar",
    "contact.info": "Información de Contacto",
    "contact.followMe": "Sígueme",
    "contact.name": "Nombre",
    "contact.email": "Email",
    "contact.subject": "Asunto",
    "contact.message": "Mensaje",
    "contact.captcha": "Verificación de Seguridad",
    "contact.send": "Enviar Mensaje",
    "footer.about": "Acerca de",
    "footer.description": "Desarrollador apasionado creando soluciones innovadoras y experiencias de usuario hermosas.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.services": "Servicios",
    "footer.social": "Redes Sociales",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.projects": "Projets",
    "nav.skills": "Compétences",
    "nav.blog": "Blog",
    "nav.testimonials": "Témoignages",
    "nav.contact": "Contact",
    "hero.title": "Bonjour, je suis Votre Nom",
    "hero.subtitle": "Développeur Full Stack et Résolveur de Problèmes Créatif",
    "hero.viewWork": "Voir Mon Travail",
    "hero.getInTouch": "Me Contacter",
    "projects.title": "Projets en Vedette",
    "projects.all": "Tous",
    "projects.web": "Apps Web",
    "projects.mobile": "Mobile",
    "projects.design": "Design",
    "skills.title": "Compétences et Expertise",
    "skills.frontend": "Développement Frontend",
    "skills.backend": "Développement Backend",
    "skills.tools": "Outils et Autres",
    "blog.title": "Derniers Articles",
    "blog.readMore": "Lire Plus →",
    "testimonials.title": "Ce Que Disent Les Clients",
    "contact.title": "Me Contacter",
    "contact.info": "Informations de Contact",
    "contact.followMe": "Me Suivre",
    "contact.name": "Nom",
    "contact.email": "Email",
    "contact.subject": "Sujet",
    "contact.message": "Message",
    "contact.captcha": "Vérification de Sécurité",
    "contact.send": "Envoyer le Message",
    "footer.about": "À Propos",
    "footer.description": "Développeur passionné créant des solutions innovantes et de belles expériences utilisateur.",
    "footer.quickLinks": "Liens Rapides",
    "footer.services": "Services",
    "footer.social": "Réseaux Sociaux",
  },
}

export const searchData = [
  { title: "Home", url: "#home", content: "portfolio developer full stack" },
  { title: "Projects", url: "#projects", content: "web development mobile apps design" },
  { title: "Skills", url: "#skills", content: "react javascript python node.js" },
  { title: "Blog", url: "#blog", content: "articles tutorials insights" },
  { title: "Testimonials", url: "#testimonials", content: "client reviews feedback" },
  { title: "Contact", url: "#contact", content: "get in touch email phone" },
]
